builds:
  - main: .
    id: "cmap"
    binary: cmap
    targets:
      - windows_arm64
      - windows_amd64
      - darwin_arm64
      - darwin_amd64
      - linux_arm64
      - linux_amd64
      - js_wasm

signs:
  - id: "cmap"
    artifacts: all
